stages:
  - build
  - test
  - cleanup
before_script:
  - export COMPOSE_PROJECT_NAME=pipeline${CI_PIPELINE_ID}
build:
  stage: build
  script:
    - docker-compose build
test:
  stage: test
  script:
    - docker-compose run roj
cleanup:
  stage: cleanup
  script:
    - docker-compose down -v --remove-orphans
  when: always