stages:
  - test
before_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}
  - export BUILD_ROJ_VERSION=$(git describe --always --long --dirty)
after_script:
  - export COMPOSE_PROJECT_NAME=buildpipeline${CI_PIPELINE_ID}
  - docker-compose down -v
test:
  stage: test
  script:
    - docker-compose build
    - docker-compose run --rm roj
    - docker-compose run --rm roj pwd
    - docker-compose run --rm roj docker-machine ls
    # do not fail, since there's no active docker connection in testing
    - docker-compose run --rm roj docker version || exit 0
    - docker-compose run --rm roj help.sh
    - docker-compose run --rm roj boilr template
    #- docker-compose run --rm roj boilr version
    - docker-compose run --rm roj ctop -v
    - docker-compose run --rm roj make